version: '3.6'
# https://docs.docker.com/compose/compose-file/

services:
  postgres:
    image: postgres:17
    container_name: postgres
    restart: unless-stopped
    volumes:
      - 'postgresdata:/var/lib/postgresql/data'
    environment:
      - POSTGRES_USER=${TYPEORM_USERNAME}
      - POSTGRES_PASSWORD=${TYPEORM_PASSWORD}
      - POSTGRES_DB=${TYPEORM_DATABASE}
    env_file:
      - .env
    ports:
      - '25434:5432'

  relayer:
    build:
      context: .
      dockerfile: local.Dockerfile
    container_name: relayer
    restart: unless-stopped
    ports:
      - '8000:8000'
    env_file:
      - .env
    depends_on:
      - postgres

volumes:
  postgresdata:
