/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers";
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common";

export type ProofOfAgreementStruct = {
  authorityCID: string;
  signatureCIDs: string[];
  app: string;
  timestamp: BigNumberish;
  metadata: string;
};

export type ProofOfAgreementStructOutput = [authorityCID: string, signatureCIDs: string[], app: string, timestamp: bigint, metadata: string] & {
  authorityCID: string;
  signatureCIDs: string[];
  app: string;
  timestamp: bigint;
  metadata: string;
};

export type SignedProofOfAgreementStruct = {
  message: ProofOfAgreementStruct;
  proofCID: string;
};

export type SignedProofOfAgreementStructOutput = [message: ProofOfAgreementStructOutput, proofCID: string] & { message: ProofOfAgreementStructOutput; proofCID: string };

export type SignerStruct = { addr: AddressLike; metadata: string };

export type SignerStructOutput = [addr: string, metadata: string] & {
  addr: string;
  metadata: string;
};

export type ProofOfAuthorityStruct = {
  name: string;
  from: AddressLike;
  agreementCID: string;
  signers: SignerStruct[];
  app: string;
  timestamp: BigNumberish;
  metadata: string;
};

export type ProofOfAuthorityStructOutput = [name: string, from: string, agreementCID: string, signers: SignerStructOutput[], app: string, timestamp: bigint, metadata: string] & {
  name: string;
  from: string;
  agreementCID: string;
  signers: SignerStructOutput[];
  app: string;
  timestamp: bigint;
  metadata: string;
};

export type SignedProofOfAuthorityStruct = {
  message: ProofOfAuthorityStruct;
  signature: BytesLike;
  proofCID: string;
};

export type SignedProofOfAuthorityStructOutput = [message: ProofOfAuthorityStructOutput, signature: string, proofCID: string] & {
  message: ProofOfAuthorityStructOutput;
  signature: string;
  proofCID: string;
};

export type ProofOfSignatureStruct = {
  name: string;
  signer: AddressLike;
  authorityCID: string;
  app: string;
  timestamp: BigNumberish;
  metadata: string;
};

export type ProofOfSignatureStructOutput = [name: string, signer: string, authorityCID: string, app: string, timestamp: bigint, metadata: string] & {
  name: string;
  signer: string;
  authorityCID: string;
  app: string;
  timestamp: bigint;
  metadata: string;
};

export type SignedProofOfSignatureStruct = {
  message: ProofOfSignatureStruct;
  signature: BytesLike;
  proofCID: string;
};

export type SignedProofOfSignatureStructOutput = [message: ProofOfSignatureStructOutput, signature: string, proofCID: string] & {
  message: ProofOfSignatureStructOutput;
  signature: string;
  proofCID: string;
};

export type EIP712PropertyTypeStruct = { name: string; type: string };

export type EIP712PropertyTypeStructOutput = [name: string, type_: string] & {
  name: string;
  type: string;
};

export type EIP712ProofOfAgreementTypesStruct = {
  EIP712Domain: [EIP712PropertyTypeStruct, EIP712PropertyTypeStruct];
  ProofOfAgreement: [EIP712PropertyTypeStruct, EIP712PropertyTypeStruct, EIP712PropertyTypeStruct, EIP712PropertyTypeStruct, EIP712PropertyTypeStruct];
};

export type EIP712ProofOfAgreementTypesStructOutput = [
  EIP712Domain: [EIP712PropertyTypeStructOutput, EIP712PropertyTypeStructOutput],
  ProofOfAgreement: [
    EIP712PropertyTypeStructOutput,
    EIP712PropertyTypeStructOutput,
    EIP712PropertyTypeStructOutput,
    EIP712PropertyTypeStructOutput,
    EIP712PropertyTypeStructOutput,
  ],
] & {
  EIP712Domain: [EIP712PropertyTypeStructOutput, EIP712PropertyTypeStructOutput];
  ProofOfAgreement: [
    EIP712PropertyTypeStructOutput,
    EIP712PropertyTypeStructOutput,
    EIP712PropertyTypeStructOutput,
    EIP712PropertyTypeStructOutput,
    EIP712PropertyTypeStructOutput,
  ];
};

export type EIP712DomainStruct = {
  name: string;
  version: string;
  chainId: BigNumberish;
  verifyingContract: AddressLike;
};

export type EIP712DomainStructOutput = [name: string, version: string, chainId: bigint, verifyingContract: string] & {
  name: string;
  version: string;
  chainId: bigint;
  verifyingContract: string;
};

export type EIP712ProofOfAgreementStruct = {
  types: EIP712ProofOfAgreementTypesStruct;
  domain: EIP712DomainStruct;
  primaryType: string;
  message: ProofOfAgreementStruct;
};

export type EIP712ProofOfAgreementStructOutput = [
  types: EIP712ProofOfAgreementTypesStructOutput,
  domain: EIP712DomainStructOutput,
  primaryType: string,
  message: ProofOfAgreementStructOutput,
] & {
  types: EIP712ProofOfAgreementTypesStructOutput;
  domain: EIP712DomainStructOutput;
  primaryType: string;
  message: ProofOfAgreementStructOutput;
};

export type SignedProofOfAgreementMsgStruct = {
  message: EIP712ProofOfAgreementStruct;
};

export type SignedProofOfAgreementMsgStructOutput = [message: EIP712ProofOfAgreementStructOutput] & { message: EIP712ProofOfAgreementStructOutput };

export type EIP712ProofOfAuthorityTypesStruct = {
  EIP712Domain: [EIP712PropertyTypeStruct, EIP712PropertyTypeStruct];
  Signer: [EIP712PropertyTypeStruct, EIP712PropertyTypeStruct];
  ProofOfAuthority: EIP712PropertyTypeStruct[];
};

export type EIP712ProofOfAuthorityTypesStructOutput = [
  EIP712Domain: [EIP712PropertyTypeStructOutput, EIP712PropertyTypeStructOutput],
  Signer: [EIP712PropertyTypeStructOutput, EIP712PropertyTypeStructOutput],
  ProofOfAuthority: EIP712PropertyTypeStructOutput[],
] & {
  EIP712Domain: [EIP712PropertyTypeStructOutput, EIP712PropertyTypeStructOutput];
  Signer: [EIP712PropertyTypeStructOutput, EIP712PropertyTypeStructOutput];
  ProofOfAuthority: EIP712PropertyTypeStructOutput[];
};

export type EIP712ProofOfAuthorityStruct = {
  types: EIP712ProofOfAuthorityTypesStruct;
  domain: EIP712DomainStruct;
  primaryType: string;
  message: ProofOfAuthorityStruct;
};

export type EIP712ProofOfAuthorityStructOutput = [
  types: EIP712ProofOfAuthorityTypesStructOutput,
  domain: EIP712DomainStructOutput,
  primaryType: string,
  message: ProofOfAuthorityStructOutput,
] & {
  types: EIP712ProofOfAuthorityTypesStructOutput;
  domain: EIP712DomainStructOutput;
  primaryType: string;
  message: ProofOfAuthorityStructOutput;
};

export type SignedProofOfAuthorityMsgStruct = {
  message: EIP712ProofOfAuthorityStruct;
  signature: BytesLike;
};

export type SignedProofOfAuthorityMsgStructOutput = [message: EIP712ProofOfAuthorityStructOutput, signature: string] & {
  message: EIP712ProofOfAuthorityStructOutput;
  signature: string;
};

export type EIP712ProofOfSignatureTypesStruct = {
  EIP712Domain: [EIP712PropertyTypeStruct, EIP712PropertyTypeStruct];
  ProofOfSignature: EIP712PropertyTypeStruct[];
};

export type EIP712ProofOfSignatureTypesStructOutput = [
  EIP712Domain: [EIP712PropertyTypeStructOutput, EIP712PropertyTypeStructOutput],
  ProofOfSignature: EIP712PropertyTypeStructOutput[],
] & {
  EIP712Domain: [EIP712PropertyTypeStructOutput, EIP712PropertyTypeStructOutput];
  ProofOfSignature: EIP712PropertyTypeStructOutput[];
};

export type EIP712ProofOfSignatureStruct = {
  types: EIP712ProofOfSignatureTypesStruct;
  domain: EIP712DomainStruct;
  primaryType: string;
  message: ProofOfSignatureStruct;
};

export type EIP712ProofOfSignatureStructOutput = [
  types: EIP712ProofOfSignatureTypesStructOutput,
  domain: EIP712DomainStructOutput,
  primaryType: string,
  message: ProofOfSignatureStructOutput,
] & {
  types: EIP712ProofOfSignatureTypesStructOutput;
  domain: EIP712DomainStructOutput;
  primaryType: string;
  message: ProofOfSignatureStructOutput;
};

export type SignedProofOfSignatureMsgStruct = {
  message: EIP712ProofOfSignatureStruct;
  signature: BytesLike;
};

export type SignedProofOfSignatureMsgStructOutput = [message: EIP712ProofOfSignatureStructOutput, signature: string] & {
  message: EIP712ProofOfSignatureStructOutput;
  signature: string;
};

export interface DAOSignAppInterface extends Interface {
  getFunction(
    nameOrSignature: "getProofOfAgreement" | "getProofOfAuthority" | "getProofOfSignature" | "storeProofOfAgreement" | "storeProofOfAuthority" | "storeProofOfSignature",
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "NewProofOfAgreement" | "NewProofOfAuthority" | "NewProofOfSignature"): EventFragment;

  encodeFunctionData(functionFragment: "getProofOfAgreement", values: [string]): string;
  encodeFunctionData(functionFragment: "getProofOfAuthority", values: [string]): string;
  encodeFunctionData(functionFragment: "getProofOfSignature", values: [string]): string;
  encodeFunctionData(functionFragment: "storeProofOfAgreement", values: [SignedProofOfAgreementStruct]): string;
  encodeFunctionData(functionFragment: "storeProofOfAuthority", values: [SignedProofOfAuthorityStruct]): string;
  encodeFunctionData(functionFragment: "storeProofOfSignature", values: [SignedProofOfSignatureStruct]): string;

  decodeFunctionResult(functionFragment: "getProofOfAgreement", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getProofOfAuthority", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getProofOfSignature", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "storeProofOfAgreement", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "storeProofOfAuthority", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "storeProofOfSignature", data: BytesLike): Result;
}

export namespace NewProofOfAgreementEvent {
  export type InputTuple = [data: SignedProofOfAgreementStruct];
  export type OutputTuple = [data: SignedProofOfAgreementStructOutput];
  export interface OutputObject {
    data: SignedProofOfAgreementStructOutput;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace NewProofOfAuthorityEvent {
  export type InputTuple = [data: SignedProofOfAuthorityStruct];
  export type OutputTuple = [data: SignedProofOfAuthorityStructOutput];
  export interface OutputObject {
    data: SignedProofOfAuthorityStructOutput;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace NewProofOfSignatureEvent {
  export type InputTuple = [data: SignedProofOfSignatureStruct];
  export type OutputTuple = [data: SignedProofOfSignatureStructOutput];
  export interface OutputObject {
    data: SignedProofOfSignatureStructOutput;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface DAOSignApp extends BaseContract {
  connect(runner?: ContractRunner | null): DAOSignApp;
  waitForDeployment(): Promise<this>;

  interface: DAOSignAppInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>;
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>;

  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>;
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(event: TCEvent): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>;

  getProofOfAgreement: TypedContractMethod<[cid: string], [SignedProofOfAgreementMsgStructOutput], "view">;

  getProofOfAuthority: TypedContractMethod<[cid: string], [SignedProofOfAuthorityMsgStructOutput], "view">;

  getProofOfSignature: TypedContractMethod<[cid: string], [SignedProofOfSignatureMsgStructOutput], "view">;

  storeProofOfAgreement: TypedContractMethod<[data: SignedProofOfAgreementStruct], [void], "nonpayable">;

  storeProofOfAuthority: TypedContractMethod<[data: SignedProofOfAuthorityStruct], [void], "nonpayable">;

  storeProofOfSignature: TypedContractMethod<[data: SignedProofOfSignatureStruct], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

  getFunction(nameOrSignature: "getProofOfAgreement"): TypedContractMethod<[cid: string], [SignedProofOfAgreementMsgStructOutput], "view">;
  getFunction(nameOrSignature: "getProofOfAuthority"): TypedContractMethod<[cid: string], [SignedProofOfAuthorityMsgStructOutput], "view">;
  getFunction(nameOrSignature: "getProofOfSignature"): TypedContractMethod<[cid: string], [SignedProofOfSignatureMsgStructOutput], "view">;
  getFunction(nameOrSignature: "storeProofOfAgreement"): TypedContractMethod<[data: SignedProofOfAgreementStruct], [void], "nonpayable">;
  getFunction(nameOrSignature: "storeProofOfAuthority"): TypedContractMethod<[data: SignedProofOfAuthorityStruct], [void], "nonpayable">;
  getFunction(nameOrSignature: "storeProofOfSignature"): TypedContractMethod<[data: SignedProofOfSignatureStruct], [void], "nonpayable">;

  getEvent(key: "NewProofOfAgreement"): TypedContractEvent<NewProofOfAgreementEvent.InputTuple, NewProofOfAgreementEvent.OutputTuple, NewProofOfAgreementEvent.OutputObject>;
  getEvent(key: "NewProofOfAuthority"): TypedContractEvent<NewProofOfAuthorityEvent.InputTuple, NewProofOfAuthorityEvent.OutputTuple, NewProofOfAuthorityEvent.OutputObject>;
  getEvent(key: "NewProofOfSignature"): TypedContractEvent<NewProofOfSignatureEvent.InputTuple, NewProofOfSignatureEvent.OutputTuple, NewProofOfSignatureEvent.OutputObject>;

  filters: {
    "NewProofOfAgreement(tuple)": TypedContractEvent<NewProofOfAgreementEvent.InputTuple, NewProofOfAgreementEvent.OutputTuple, NewProofOfAgreementEvent.OutputObject>;
    NewProofOfAgreement: TypedContractEvent<NewProofOfAgreementEvent.InputTuple, NewProofOfAgreementEvent.OutputTuple, NewProofOfAgreementEvent.OutputObject>;

    "NewProofOfAuthority(tuple)": TypedContractEvent<NewProofOfAuthorityEvent.InputTuple, NewProofOfAuthorityEvent.OutputTuple, NewProofOfAuthorityEvent.OutputObject>;
    NewProofOfAuthority: TypedContractEvent<NewProofOfAuthorityEvent.InputTuple, NewProofOfAuthorityEvent.OutputTuple, NewProofOfAuthorityEvent.OutputObject>;

    "NewProofOfSignature(tuple)": TypedContractEvent<NewProofOfSignatureEvent.InputTuple, NewProofOfSignatureEvent.OutputTuple, NewProofOfSignatureEvent.OutputObject>;
    NewProofOfSignature: TypedContractEvent<NewProofOfSignatureEvent.InputTuple, NewProofOfSignatureEvent.OutputTuple, NewProofOfSignatureEvent.OutputObject>;
  };
}
