name: Build & Push (TradeFi)

on:
  push:
    branches:
      - main
      - tradefi

env:
  DO_CONTAINER_REGISTRY: "daosign-container-registry"

jobs:
  build:
    name: Run docker build
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{steps.vars.outputs.tag}}
    steps:
      - uses: actions/checkout@v3
      - name: Get the version
        id: vars
        run: echo "tag=$(echo ${GITHUB_SHA:0:7})" >> $GITHUB_OUTPUT
      - name: Build the Docker image
        run: docker build -t tradefi-relayer-dev:${{ steps.vars.outputs.tag }} .
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_ACCESS_TOKEN }}
      - name: Log in to DigitalOcean Container Registry
        run: doctl registry login --expiry-seconds 600
      - name: Tag image
        run: |
          docker tag tradefi-relayer-dev:${{ steps.vars.outputs.tag }} \
          registry.digitalocean.com/${{ env.DO_CONTAINER_REGISTRY }}/tradefi-relayer-dev:${{ steps.vars.outputs.tag }}
      - name: Push to DigitalOcean Container Registry
        run: |
          docker push registry.digitalocean.com/${{ env.DO_CONTAINER_REGISTRY }}/tradefi-relayer-dev:${{ steps.vars.outputs.tag }}
  deploy:
    name: Run helm upgrade
    runs-on: ubuntu-latest
    needs: [build]
    env:
      # Ingress
      HOST: 'relayer.dev.tradefi.daosign.org'
      # Secrets
      DB_PORT: '25060'
      DATABASE: 'tradefi-relayer-dev'
      LOGGING: 'false'
      ETH_RPC_URL: 'https://rpc.ankr.com/eth_goerli'
    steps:
      - uses: actions/checkout@v3
      - name: Create & View .env.yaml file
        id: create-env
        run: |
          cat << EOF > .env.yaml
          {
            "ingress": {
              "host": "${{ env.HOST }}"
            },
            "secrets": {
              "dbPort": "${{ env.DB_PORT }}",
              "database": "${{ env.DATABASE }}",
              "host": "${{ secrets.DO_DB_HOST_DEV }}",
              "username": "${{ secrets.DO_DB_USERNAME_DEV }}",
              "password": "${{ secrets.DO_DB_PASSWORD_DEV }}",
              "logging": "${{ env.LOGGING }}",
              "ethRpcUrl": "${{ env.ETH_RPC_URL }}",
              "ethPrivateKey": "${{ secrets.ETH_PRIVATE_KEY_DEV }}",
              "ethContractAddress": "${{ secrets.ETH_CONTRACT_ADDRESS_DEV }}"
            }
          }
          EOF
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_ACCESS_TOKEN }}
      - name: Save DigitalOcean kubeconfig
        run: doctl kubernetes cluster kubeconfig save daosign-kubernetes-cluster-dev
      - name: Helm deploy the latest image
        env:
          NAMESPACE: "tradefi-dev"
          HELM_VERSION: 0.1.1
        run: |
          doctl registry login --expiry-seconds 600 && \
          kubectl get pods -n ${{ env.NAMESPACE }} && helm ls -n ${{ env.NAMESPACE }} && \
          helm upgrade helm-relayer -i -n ${{ env.NAMESPACE }} --atomic -f .env.yaml oci://registry.digitalocean.com/${{ env.DO_CONTAINER_REGISTRY }}/helm-relayer --version $HELM_VERSION \
          --set=backend.image.repository=registry.digitalocean.com/${{ env.DO_CONTAINER_REGISTRY }}/tradefi-relayer-dev,backend.image.tag=${{needs.build.outputs.image_tag}} && \
          helm ls -n ${{ env.NAMESPACE }} && kubectl get pods -n ${{ env.NAMESPACE }}
