name: Build & Push Production Release

on:
  push:
    tags: ["v*.*.*"]

env:
  DO_CONTAINER_REGISTRY: "daosign-container-registry"

jobs:
  build:
    name: Run docker build
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{steps.vars.outputs.tag}}
    steps:
      - uses: actions/checkout@v3
      - name: Get the version
        id: vars
        run: echo "tag=$(echo ${GITHUB_REF#refs/tags/})" >> $GITHUB_OUTPUT
      - name: Build the Docker image
        run: docker build -t prod-relayer:${{ steps.vars.outputs.tag }} .
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_ACCESS_TOKEN }}
      - name: Log in to DigitalOcean Container Registry
        run: doctl registry login --expiry-seconds 600
      - name: Tag image
        run: |
          docker tag prod-relayer:${{ steps.vars.outputs.tag }} \
          registry.digitalocean.com/${{ env.DO_CONTAINER_REGISTRY }}/prod-relayer:${{ steps.vars.outputs.tag }}
      - name: Push to DigitalOcean Container Registry
        run: |
          docker push registry.digitalocean.com/${{ env.DO_CONTAINER_REGISTRY }}/prod-relayer:${{ steps.vars.outputs.tag }}
  deploy:
    name: Run helm upgrade
    runs-on: ubuntu-latest
    needs: [build]
    env:
      # Ingress
      HOST: "relayer.daosign.org"
      # Secrets
      DB_PORT: "25060"
      DATABASE: "daosign-relayer-prod"
      LOGGING: "false"
      ETH_RPC_URL: "https://rpc.ankr.com/eth_goerli"
      SUI_RPC_TYPE: "testnet"
      GRAYLOG_HOST: "45.55.98.77"
      GRAYLOG_PORT: "12201"
      OASIS_RPC_URL: "https://testnet.sapphire.oasis.dev"
      STORAGE_RPC_URL: "https://optimism-sepolia.blockpi.network/v1/rpc/public"
      APP_NAME: "daoSign-prod"
    steps:
      - uses: actions/checkout@v3
      - name: Create & View .env.yaml file
        id: create-env
        run: |
          cat << EOF > .env.yaml
          {
            "ingress": {
              "host": "${{ env.HOST }}"
            },
            "secrets": {
              "dbPort": "${{ env.DB_PORT }}",
              "database": "${{ env.DATABASE }}",
              "host": "${{ secrets.DO_DB_HOST_PROD }}",
              "username": "${{ secrets.DO_DB_USERNAME_PROD }}",
              "password": "${{ secrets.DO_DB_PASSWORD_PROD }}",
              "logging": "${{ env.LOGGING }}",
              "ethRpcUrl": "${{ env.ETH_RPC_URL }}",
              "ethPrivateKey": "${{ secrets.ETH_PRIVATE_KEY_DEV }}",
              "ethContractAddress": "${{ secrets.ETH_CONTRACT_ADDRESS_DEV }}",
              "suiRpcType": "${{ env.SUI_RPC_TYPE }}",
              "suiPackageId": "${{ secrets.SUI_PACKAGE_ID_DEV }}",
              "suiBagId": "${{ secrets.SUI_BAG_ID_DEV }}",
              "suiMnemonic": "${{ secrets.SUI_MNEMONIC_DEV }}",
              "graylogHost": "${{ env.GRAYLOG_HOST }}",
              "graylogPort": "${{ env.GRAYLOG_PORT }}",
              "oasisRpcUrl": "${{ env.OASIS_RPC_URL }}",
              "oasisContractAddress": "${{ secrets.OASIS_CONTRACT_ADDRESS_DEV }}",
              "oasisPrivateKey": "${{ secrets.OASIS_PRIVATE_KEY_DEV }}",
              "storageRpcUrl": "${{ env.STORAGE_RPC_URL }}",
              "storageContractAddress": "${{ secrets.STORAGE_CONTRACT_ADDRESS_DEV }}",
              "storageAdminPrivateKey": "${{ secrets.STORAGE_ADMIN_PRIVATE_KEY_DEV }}",
              "appName": "${{ env.APP_NAME }}",
              "appSlackWebhookLink": "${{ secrets.APP_SLACK_WEBHOOK_LINK_DEV }}"
            }
          }
          EOF
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_ACCESS_TOKEN }}
      - name: Save DigitalOcean kubeconfig
        run: doctl kubernetes cluster kubeconfig save daosign-kubernetes-cluster-prod
      - name: Helm deploy the latest image
        env:
          HELM_VERSION: 0.1.6
        run: |
          doctl registry login --expiry-seconds 600 && \
          kubectl get pods && helm ls && \
          helm upgrade helm-relayer -i --atomic -f .env.yaml oci://registry.digitalocean.com/${{ env.DO_CONTAINER_REGISTRY }}/helm-relayer --version $HELM_VERSION \
          --set=relayer.image.repository=registry.digitalocean.com/${{ env.DO_CONTAINER_REGISTRY }}/prod-relayer,relayer.image.tag=${{needs.build.outputs.image_tag}} && \
          helm ls && kubectl get pods
